import { z } from 'zod';

export const projectSchema = z.object({
  slug: z.string().min(2, 'Slug is required'),
  name_en: z.string().min(2, 'English name is required'),
  name_ta: z.string().min(2, 'Tamil name is required'),
  category: z.string().min(2, 'Category is required'),
  service: z.string().min(2, 'Service type is required'),
  location: z.string().min(2, 'Location is required'),
  year: z.number().int().min(1900).max(2100),
  status: z.enum(['completed', 'ongoing', 'upcoming']),
  built_up_area: z.string().optional().nullable(),
  plot_area: z.string().optional().nullable(),
  floors: z.number().int().optional().nullable(),
  bedrooms: z.number().int().optional().nullable(),
  short_description_en: z.string().min(10, 'Short description in English is required'),
  short_description_ta: z.string().min(10, 'Short description in Tamil is required'),
  overview_en: z.string().min(20, 'Overview in English is required'),
  overview_ta: z.string().min(20, 'Overview in Tamil is required'),
  design_description_en: z.string().optional().nullable(),
  design_description_ta: z.string().optional().nullable(),
  construction_description_en: z.string().optional().nullable(),
  construction_description_ta: z.string().optional().nullable(),
  interior_description_en: z.string().optional().nullable(),
  interior_description_ta: z.string().optional().nullable(),
  key_features_en: z.array(z.string()).default([]),
  key_features_ta: z.array(z.string()).default([]),
  map_url: z.string().url().optional().nullable().or(z.literal('')),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  cover_image_url: z.string().url('Valid cover image URL is required'),
  cover_image_public_id: z.string().min(1, 'Cover image public ID is required'),
  seo_title_en: z.string().optional().nullable(),
  seo_title_ta: z.string().optional().nullable(),
  seo_description_en: z.string().optional().nullable(),
  seo_description_ta: z.string().optional().nullable(),
  published: z.boolean().default(false),
});

export type ProjectInput = z.infer<typeof projectSchema>;
